# -*- coding: utf-8 -*-
"""volume_of_sphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDY4kdN3LBDRbTtQ6lYFPbLWN-Os1gEF
"""

def calculate_volume_of_sphere(radius):
  pi = 3.14
  volume = (4/3) * pi * (radius*radius*radius)
  return volume

print(f"The volume of a sphere with a radii of 30 is:", calculate_volume_of_sphere(30))
print(f"The volume of a sphere with a radii of 40 is:", calculate_volume_of_sphere(40))